version: "3"
services:
  mysql-source:
    image: mysql:8.0
    container_name: mysql-source
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
  mysql-replica:
    image: mysql:8.0
    container_name: mysql-replica
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
