version: '3.8'

services:
  postgres:
    image: postgres:16.4
    container_name: postgres
    ports:
      - '5555:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: netflix
