[project]
name = "llmops-lab"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "imkdw", email = "imkdw@kakao.com" }
]
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.141.1",
    "jinja2>=3.1.6",
    "langfuse>=4.15.4",
    "python-dotenv>=1.2.3",
    "python-multipart>=0.0.32",
    "uvicorn>=0.53.0",
]

[project.scripts]
llmops-lab = "llmops_lab:main"

[build-system]
requires = ["uv_build>=0.12.13,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pytest>=9.1.1",
]

[tool.pytest.ini_options]
pythonpath = ["."]
