export const NOTIFICATION_SERVICE = 'NOTIFICATION_SERVICE';
export const USER_SERVICE = 'USER_SERVICE';
export const ORDER_SERVICE = 'ORDER_SERVICE';
export const PRODUCT_SERVICE = 'PRODUCT_SERVICE';
export const PAYMENT_SERVICE = 'PAYMENT_SERVICE';
